# Generated by Django 2.2.14 on 2020-07-20 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='phonenumber',
            options={'managed': False},
        ),
    ]
